export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROS = "GET_USER_ERROS";
export const SET_DISPLAY = "SET_DISPLAY";
export const GET_ITEM_USER="GET_ITEM_USER";
export const GET_SUCCES_ITEM_USER="GET_SUCCES_ITEM_USER";